/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;


/**
 *
 * @author Erasmo
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor3 = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValor4 = new javax.swing.JTextField();
        panelOperaciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Básica");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        plValores.setBackground(new java.awt.Color(153, 153, 153));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Respuesta:");
        plValores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtValor1.setEditable(false);
        txtValor1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 130, 60));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Valor 1:");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Convertir grados ");
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel3KeyTyped(evt);
            }
        });
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 60));

        txtValor3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtValor3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor3ActionPerformed(evt);
            }
        });
        txtValor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor3KeyTyped(evt);
            }
        });
        plValores.add(txtValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, -1));

        txtvalor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtvalor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorKeyTyped(evt);
            }
        });
        plValores.add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 30));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Valor 2:");
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel10KeyTyped(evt);
            }
        });
        plValores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtValor4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtValor4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor4ActionPerformed(evt);
            }
        });
        txtValor4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor4KeyTyped(evt);
            }
        });
        plValores.add(txtValor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 260));

        panelOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sumar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        jButton2.setText("Restar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        jButton3.setText("Multiplicar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jButton4.setText("Dividir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, -1));

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 50));

        jButton6.setText("Celsius a Farenheit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton7.setText("Farenheit a Celsius");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelOperaciones.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        getContentPane().add(panelOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 220, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validarCampos();
        sumarValores();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validarCampos(){
        if(txtvalor.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio.");
            txtvalor.requestFocus();
        }else if(txtValor4.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 2, porque el campo esta vacio.");
            txtValor4.requestFocus();
        }
        
      
    }
    
    private void sumarValores(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta = cal.sumar(Double.parseDouble(txtvalor.getText()), Double.parseDouble(txtValor4.getText()));
        txtValor1.setText(respuesta + "");
    }
    private void limpiarCampos(){
        txtvalor.setText("");
        txtValor3.setText("");
        txtValor4.setText("");
        txtValor1.setText("");
        txtvalor.requestFocus();
    }
    private void restarValores(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta = cal.restar(Double.parseDouble(txtvalor.getText()), Double.parseDouble(txtValor4.getText()));
        txtValor1.setText(respuesta + "");
    }
    private void multiplicarValores(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtvalor.getText()), Double.parseDouble(txtValor4.getText()));
        txtValor1.setText(respuesta + "");
    }
    private void divirdirValores(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta = cal.dividir(Double.parseDouble(txtvalor.getText()), Double.parseDouble(txtValor4.getText()));
        txtValor1.setText(respuesta + "");
    }
    private void convertirAFarenheit(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta = cal.convertirAFarenheit(Double.parseDouble(txtValor3.getText()));
        txtValor1.setText(respuesta + "");
    }
    private void convertirACelsius(){
        CalculadoraClase cal = new CalculadoraClase();
        Double respuesta  = cal.convertirACelsius(Double.parseDouble(txtValor3.getText()));
        txtValor1.setText(respuesta + "");
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyTyped

    private void txtValor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor3KeyTyped
       char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros >'9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null,"Favor ingresar numeros para realizar la operacion");
            evt.consume();
      }
    }//GEN-LAST:event_txtValor3KeyTyped

    private void txtvalorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorKeyTyped
       char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros >'9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null,"Favor ingresar numeros para realizar la operacion");
            evt.consume();
    } 
    }//GEN-LAST:event_txtvalorKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        validarCampos();
        divirdirValores();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10KeyTyped

    private void txtValor4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor4KeyTyped
       char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros >'9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null,"Favor ingresar numeros para realizar la operacion");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor4KeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        convertirACelsius();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtValor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor4ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtValor4ActionPerformed

    private void txtValor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        convertirAFarenheit();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor3;
    private javax.swing.JTextField txtValor4;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}


